// i18n.ts — 轻量中英双语支持（zh / en）
// 设计：zustand 极小语言 store（localStorage 持久化，挂载后 rehydrate 防 SSR 水合不匹配）
// + 元组字典 [zh, en] + 标签表（节点类型 / 关系 / 阶段 / 面孔）。
// Agent 产出语言由前端随请求透传 lang 到 agent-service，后端按会话注入语言指令。
import { useCallback } from 'react';
import { create } from 'zustand';
import type { AgentFace, AgentStatus, EdgeRelation, EvidenceLevel, NodeKind, SessionPhase } from './types';

export type Lang = 'zh' | 'en';
const STORAGE_KEY = 'serendip-lang';

/* ---------------- 语言 store ---------------- */

export const useI18n = create<{ lang: Lang; setLang: (l: Lang) => void }>((set) => ({
  lang: 'zh',
  setLang: (lang) => {
    set({ lang });
    if (typeof document !== 'undefined') {
      try {
        localStorage.setItem(STORAGE_KEY, lang);
      } catch {
        /* ignore */
      }
      document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en';
    }
  },
}));

/** 挂载后调用：从 localStorage 恢复语言（首帧渲染 zh 与服务端一致，避免水合不匹配） */
export function rehydrateLang(): void {
  if (typeof window === 'undefined') return;
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved === 'en' || saved === 'zh') {
      useI18n.getState().setLang(saved);
    }
  } catch {
    /* ignore */
  }
}

/** 非组件场景（store action 内）读取当前语言 */
export function currentLang(): Lang {
  return useI18n.getState().lang;
}

export function localeOf(lang: Lang): string {
  return lang === 'zh' ? 'zh-CN' : 'en-US';
}

/* ---------------- 字典 ---------------- */

const DICT = {
  /* 顶栏 */
  'brand.tagline': ['生物科研灵感引擎 · 证据墙', 'Bio-research Inspiration Engine · EVIDENCE WALL'],
  'session.newProject': ['新课题', 'New Project'],
  'menu.projects': ['研究课题', 'Research Projects'],
  'menu.noProjects': ['暂无课题', 'No projects yet'],
  'menu.newProject': ['新建课题', 'New project'],
  'menu.loadDemo': ['载入示例课题（线粒体之谜）', 'Load demo (mito genome)'],
  'menu.delete': ['删除当前课题', 'Delete current project'],
  'menu.confirmDelete': ['确认删除「{title}」？此操作不可撤销。', 'Delete “{title}”? This cannot be undone.'],
  'menu.evidenceCount': ['{n} 证据', '{n} cards'],
  'phase.done': ['已完成', 'Completed'],
  'steps.title': ['步骤 {used}/{max}', 'Step {used}/{max}'],
  'sse.ok': ['实时连接正常', 'Live connection OK'],
  'sse.down': ['实时连接断开，正在重连…', 'Connection lost — reconnecting…'],
  'research.start': ['开始研究', 'Start Research'],
  'research.continue': ['继续研究', 'Continue Research'],
  'control.pause': ['暂停', 'Pause'],
  'control.resume': ['继续', 'Resume'],
  'control.stop': ['终止', 'Stop'],
  'export.title': ['导出研究简报', 'Export a research brief'],
  'export.brief': ['简报', 'Brief'],
  'export.docTitle': ['# {title} · 研究简报', '# {title} · Research Brief'],
  'export.byline': ['> 由 Serendip Lab（生物科研灵感引擎）生成 · {time}', '> Generated by Serendip Lab · {time}'],
  'export.review': ['## 研究综述', '## Research Review'],
  'export.questions': ['## 值得进一步研究的问题', '## Questions Worth Pursuing'],
  'export.recommended': ['⭐ 推荐深挖', '⭐ Recommended'],
  'export.scores': ['新颖性 {n}/5 · 可行性 {f}/5 · 影响力 {i}/5', 'Novelty {n}/5 · Feasibility {f}/5 · Impact {i}/5'],
  'export.rationale': ['理由：{text}', 'Rationale: {text}'],
  'export.wall': ['## 证据墙清单', '## Evidence Index'],
  'export.downloaded': ['简报已下载', 'Brief downloaded'],
  'export.menuTitle': ['导出', 'Export'],
  'export.menuHint': ['带走你的研究成果', 'Take your research with you'],
  'export.mdItem': ['Markdown 研究简报', 'Markdown research brief'],
  'export.mdItemDesc': ['综述 · 问题清单 · 深研方向 · 探索方案与反馈 · 证据墙', 'Review · questions · paths · plans & feedback · wall'],
  'export.bibItem': ['BibTeX 文献库', 'BibTeX library'],
  'export.bibItemDesc': ['证据墙文献源（.bib，可导入文献管理器）', 'Wall literature sources (.bib, imports into citation managers)'],
  'export.bibEmpty': ['证据墙上还没有可导出的文献源卡片', 'No literature-source cards on the wall yet'],
  'export.bibDownloaded': ['BibTeX 已下载（{n} 条文献）', 'BibTeX downloaded ({n} entries)'],
  'export.bibStarItem': ['加星文献 · 精读清单', 'Starred · reading list'],
  'export.bibStarItemDesc': ['仅导出加星文献卡（.bib 精读清单）', 'Starred cards only (.bib reading list)'],
  'export.bibStarEmpty': ['还没有加星且带文献标识的卡片——先在证据墙上给关键文献点亮星标', 'No starred literature cards yet — star key cards on the wall first'],
  'export.directions': ['## 深研方向', '## Research Paths'],
  'export.dirWhy': ['**为什么值得做**：{text}', '**Why it matters**: {text}'],
  'export.dirPlan': ['**研究目标**：{text}', '**Objective**: {text}'],
  'export.dirQuestions': ['**关键问题**', '**Key questions**'],
  'export.dirApproach': ['**分阶段路线**', '**Phased route**'],
  'export.dirMethods': ['**方法与资源**：{text}', '**Methods & resources**: {text}'],
  'export.dirOutcome': ['**预期产出**：{text}', '**Expected outcome**: {text}'],
  'export.dirRisks': ['**风险与对策**：{text}', '**Risks & mitigation**: {text}'],
  'export.dirLiterature': ['**深读文献**', '**Key literature**'],
  'export.explorations': ['## 课题探索方案与反馈记录', '## Topic Exploration Plans & Feedback Log'],
  'export.expPlan': ['### {title} · 探索方案 v{n}', '### {title} · Exploration plan v{n}'],
  'export.expObjective': ['- **目标**：{text}', '- **Objective**: {text}'],
  'export.expHypothesis': ['- **待验证假说**：{text}', '- **Hypothesis**: {text}'],
  'export.expDesign': ['- **实验设计**', '- **Design**'],
  'export.expMetrics': ['- **判读标准**：{text}', '- **Readout criteria**: {text}'],
  'export.expRound': ['#### 第 {n} 轮反馈 · {verdict}', '#### Round {n} feedback · {verdict}'],
  'export.expRoundFeedback': ['- **你的反馈**：{text}', '- **Your feedback**: {text}'],
  'export.expRoundAnalysis': ['- **推导分析**：{text}', '- **Reasoning**: {text}'],
  'export.expRoundWall': ['- **证据墙整理**', '- **Wall updates**'],
  'export.expRoundNext': ['- **下一步方向**', '- **Next steps**'],
  'toast.projectCreated': ['新课题已创建', 'New project created'],
  'toast.demoLoaded': ['示例课题已载入', 'Demo project loaded'],
  'toast.deleted': ['已删除', 'Deleted'],
  'toast.deleteFailed': ['删除失败：{msg}', 'Failed to delete: {msg}'],
  'toast.createFailed': ['创建失败：{msg}', 'Failed to create: {msg}'],
  'toast.loadFailed': ['载入失败：{msg}', 'Failed to load: {msg}'],
  'settings.llmTitle': ['LLM 配置（供应商 / 模型 / 长链推理）', 'LLM settings (provider / model / reasoning)'],
  'theme.toggle': ['切换明暗模式', 'Toggle theme'],
  'lang.toggle': ['切换语言 / Switch language', 'Switch language / 切换语言'],

  /* 对谈面板 */
  'chat.title': ['对谈室', 'Interview Room'],
  'chat.sub': ['SOCRATIC ROOM', 'SOCRATIC ROOM'],
  'chat.offline': ['离线重连中', 'Reconnecting…'],
  'chat.introTitle': ['你好，我是 Serendip 🔍', 'Hi, I’m Serendip 🔍'],
  'chat.introBody': [
    '一位生物科研合作助手。告诉我最近让你好奇的现象——哪怕只是一团模糊的直觉。我会通过追问帮你把它磨成值得研究的科学问题，然后自主检索文献与数据库，把证据钉上右边的证据墙。',
    'Your bio-research thinking partner. Tell me what has sparked your curiosity lately — even a fuzzy hunch. Through one question at a time, I’ll help you sharpen it into a researchable scientific question, then autonomously search literature and databases, pinning the evidence onto the wall.',
  ],
  'chat.introTopics': ['从这些谜题开始，或直接说出你的好奇心：', 'Start from one of these puzzles, or just describe your curiosity:'],
  'chat.typing': ['Serendip 正在思考…', 'Serendip is thinking…'],
  'chat.questionBadge': ['需要你的回答', 'Your input needed'],
  'chat.synthesisBadge': ['研究综述', 'Research review'],
  'chat.steerBadge': ['素材补充 · Agent 将在检查点纳入', 'Note added · folded in at the next checkpoint'],
  'chat.liveTitle': ['Agent 工作中', 'Agent at work'],
  'chat.liveSteps': ['{used}/{max} 步', '{used}/{max} steps'],
  'chat.liveLog': ['全程记录', 'Full log'],
  'chat.liveDeploying': ['正在规划下一步…', 'Planning the next move…'],
  'chat.ctaStart': ['进入自主研究', 'Start autonomous research'],
  'chat.ctaContinue': ['继续自主研究', 'Continue autonomous research'],
  'chat.ctaSub': [
    'Agent 将检索 PubMed / OpenAlex / UniProt 等数据库，把证据钉上证据墙',
    'The agent will search PubMed / OpenAlex / UniProt and pin evidence onto the wall',
  ],
  'chat.awaitingHint': ['Serendip 在等你的回答——你的回复将直接推进研究', 'Serendip is waiting — your reply will directly steer the research'],
  'chat.phInvestigating': ['可随时补充素材或纠正方向，Agent 将在检查点纳入…', 'Add a note or steer the direction anytime — folded in at the next checkpoint…'],
  'chat.phAwaiting': ['回答 Serendip 的问题…', 'Answer Serendip’s question…'],
  'chat.phIdle': ['说说让你好奇的生物现象…（Enter 发送）', 'Describe a biological phenomenon that intrigues you… (Enter to send)'],
  'chat.send': ['发送', 'Send'],
  'chat.sendFailed': ['发送失败', 'Failed to send'],

  /* 工作区标签 */
  'tab.canvas': ['证据墙', 'Evidence Wall'],
  'tab.narrative': ['研究综述', 'Review'],
  'tab.questions': ['问题清单', 'Questions'],
  'tab.directions': ['深研方向', 'Research Paths'],
  'tab.activity': ['活动日志', 'Activity'],

  /* 研究综述标签页 */
  'narrative.planTitle': ['研究计划 · 第 {n} 轮', 'Research plan · Round {n}'],
  'narrative.hypotheses': ['待验证假说', 'Hypotheses to test'],
  'narrative.emptyTitle': ['尚无研究综述', 'No review yet'],
  'narrative.emptyBody': [
    '进入自主研究后，Serendip 会定期把碎片化的证据梳理成有逻辑的叙事——从现象与矛盾讲到证据链，再讲到值得深挖的问题。',
    'Once autonomous research starts, Serendip periodically weaves the scattered evidence into a coherent narrative — from phenomena and contradictions to evidence chains and questions worth pursuing.',
  ],
  'narrative.ctaTitle': ['这些证据通向哪条研究路线？', 'Where do these evidence lead?'],
  'narrative.ctaBody': [
    '让 Serendip 从证据链提炼 3-4 个值得深入研究的方向，每个附完整研究计划。',
    'Let Serendip distill 3-4 research-worthy directions from the evidence chain, each with a full research plan.',
  ],
  'narrative.ctaButton': ['提炼深研方向', 'Distill research paths'],
  'narrative.resync': ['重梳理', 'Re-synthesize'],
  'narrative.resyncHint': ['证据墙变化后（补充素材/反馈证据），按当前墙上内容重新生成研究综述', 'Re-generate the review from the current wall (after new clues or feedback evidence)'],
  'narrative.resyncBusy': ['正在重新梳理综述…', 'Re-synthesizing the review…'],
  'narrative.resyncDone': ['综述已按最新证据墙重新梳理', 'Review re-synthesized from the latest wall'],

  /* 延迟收官横幅（Task 23：最终综述因配额受限未完成 → 可自动/手动补齐） */
  'narrative.pendingTitle': ['最终综述尚未完成', 'The final review is incomplete'],
  'narrative.pendingBody': [
    '上一轮研究收官时模型服务受限（如配额耗尽），最终综述未能生成。已自动重试 {n} 次，配额恢复后系统会继续自动补收官，也可以现在手动补齐。',
    'The model service was limited (e.g. quota exhausted) when the last research run wrapped up, so the final review was not generated. Auto-retried {n} time(s); the system will keep finalizing once the service recovers — or finalize it now.',
  ],
  'narrative.finalizeButton': ['立即补收官', 'Finalize now'],
  'narrative.finalizeBusy': ['正在补收官…', 'Finalizing…'],
  'narrative.finalizeDone': ['补收官完成：最终综述已补齐', 'Finalization done: the final review is ready'],

  /* 问题清单标签页 */
  'question.novelty': ['新颖性', 'Novelty'],
  'question.feasibility': ['可行性', 'Feasibility'],
  'question.impact': ['影响力', 'Impact'],
  'question.recommended': ['推荐深挖', 'Recommended'],
  'question.refs': ['证据支撑：', 'Evidence: '],
  'question.emptyTitle': ['问题清单还是空的', 'No questions yet'],
  'question.emptyBody': [
    '研究推进到检查点时，Serendip 会评估当前证据，挑出值得进一步研究的科学问题——按新颖性、可行性、影响力打分，并标出最值得深挖的一个。',
    'At each checkpoint Serendip evaluates the evidence and surfaces scientific questions worth pursuing — scored by novelty, feasibility and impact, with the most promising one highlighted.',
  ],
  'question.header': ['SERENDIP 的推荐 · 供参考，最终判断权在你', 'SERENDIP suggestions · for reference — the final call is yours'],
  'question.canvasHint': [
    '这些课题已同步钉在证据墙右侧课题栏（金箔课题卡，含支撑证据连线）→ 点击前往',
    'These topics are also pinned in the wall’s rightmost topic column (gold cards with evidence links) → open the wall',
  ],

  /* 深研方向标签页 */
  'dir.novelty': ['新颖', 'Novelty'],
  'dir.feasibility': ['可行', 'Feasible'],
  'dir.impact': ['影响', 'Impact'],
  'dir.anchors': ['证据锚点：', 'Anchors: '],
  'dir.plan': ['研究计划', 'Research Plan'],
  'dir.objective': ['研究目标', 'Objective'],
  'dir.keyQuestions': ['关键问题', 'Key questions'],
  'dir.approach': ['实施路线', 'Roadmap'],
  'dir.methods': ['方法与资源', 'Methods & resources'],
  'dir.outcome': ['预期产出', 'Expected outcome'],
  'dir.risks': ['风险与对策', 'Risks & mitigation'],
  'dir.literature': ['深读文献', 'Key literature'],
  'dir.busyTitle': ['首席战略顾问正在审阅证据链…', 'The strategy advisor is reviewing the evidence chain…'],
  'dir.busyBody': [
    'Serendip 会把整面证据墙——问题、假说、证据与矛盾——重新过一遍，提炼 3-4 个值得深挖的研究方向，并为每个方向制定完整研究计划。通常需要 30-90 秒，完成后自动出现在这里。',
    'Serendip re-reads the whole wall — questions, hypotheses, evidence and contradictions — then distills 3-4 directions worth deep study, each with a complete research plan. Usually 30-90 seconds; results appear here automatically.',
  ],
  'dir.emptyTitle': ['还没有深研方向', 'No research paths yet'],
  'dir.emptyBody': [
    '研究告一段落后，让 Serendip 站在 PI 的视角审视证据链：从矛盾、例外与缺口中提炼值得深入研究的方向，每个方向附目标、关键问题、分阶段路线与深读文献。',
    'After a research run, let Serendip review the evidence chain as a PI would: distill directions worth deep study from contradictions, exceptions and gaps — each with an objective, key questions, a staged roadmap and key literature.',
  ],
  'dir.emptyButton': ['从证据链提炼深研方向', 'Distill research paths'],
  'dir.tooFew': ['证据不足（{n}/3 节点）', 'Not enough evidence ({n}/3 cards)'],
  'dir.tooFewHint': [
    '先让 Serendip 完成至少一轮自主研究，证据墙上有素材后再来提炼。',
    'Let Serendip finish at least one autonomous run first, then distill from a populated wall.',
  ],
  'dir.resultHeader': ['深研方向 · 从证据链提炼', 'Research paths · distilled from the evidence chain'],
  'dir.disclaimer': ['SERENDIP 的建议 · 供选题参考，最终判断权在你', 'SERENDIP suggestions · for reference — the final call is yours'],
  'dir.regenerate': ['重新提炼', 'Redistill'],
  'dir.tooFewToast': ['证据墙节点太少——先完成一轮自主研究，再来提炼深研方向', 'Too few cards on the wall — finish a research run first'],
  'dir.failedToast': ['深研方向生成启动失败：{msg}', 'Failed to start path distillation: {msg}'],

  /* 课题探索闭环（Task 16） */
  'explore.title': ['课题探索', 'Topic Exploration'],
  'explore.badge': ['方案 v{n}', 'Plan v{n}'],
  'explore.planHeader': ['探索方案 · v{n}', 'EXPLORATION PLAN · v{n}'],
  'explore.objective': ['探索目标', 'Objective'],
  'explore.hypothesis': ['待验证假说', 'Hypothesis'],
  'explore.keyQuestions': ['关键问题', 'Key questions'],
  'explore.design': ['实验设计（含决策点）', 'Experiment design'],
  'explore.methods': ['方法与资源', 'Methods & resources'],
  'explore.metrics': ['判读标准', 'Readout criteria'],
  'explore.outcome': ['预期产出', 'Expected outcome'],
  'explore.risks': ['风险与对策', 'Risks & mitigation'],
  'explore.regenerate': ['重新生成', 'Redraft'],
  'explore.copy': ['复制 Markdown', 'Copy Markdown'],
  'explore.copied': ['方案已复制到剪贴板（含 {n} 轮反馈记录）', 'Plan copied to clipboard ({n} feedback rounds included)'],
  'explore.copyFailed': ['复制失败：{msg}', 'Copy failed: {msg}'],
  'explore.emptyTitle': ['还没有探索方案', 'No exploration plan yet'],
  'explore.emptyBody': [
    '让实验设计顾问为这个课题制定一份可落地的探索方案——目标、分阶段实验设计、判读标准与决策点。按方案推进后回来反馈结果，Serendip 会继续推导、重整证据墙逻辑并给出下一步方向。',
    'Let the experiment-design advisor draft a concrete plan for this topic — objective, staged design, readout criteria and decision points. After you run a step, come back with results and Serendip keeps reasoning, re-organizes the wall and proposes next steps.',
  ],
  'explore.emptyButton': ['生成探索方案', 'Draft the plan'],
  'explore.busyTitle': ['实验设计顾问正在起草方案…', 'The advisor is drafting the plan…'],
  'explore.busyBody': [
    '衔接课题的支撑证据与已知矛盾，输出目标、分阶段实验设计、判读标准与决策点。通常需要 30-90 秒。',
    'Linking the topic to its supporting evidence and known contradictions. Usually 30-90 seconds.',
  ],
  'explore.round': ['第 {n} 轮', 'Round {n}'],
  'explore.roundFeedback': ['你的反馈', 'Your feedback'],
  'explore.analysis': ['推导分析', 'Reasoning'],
  'explore.logicUpdates': ['证据墙整理', 'Wall updates'],
  'explore.nextSteps': ['下一步方向', 'Next steps'],
  'explore.planUpdated': ['探索路线已修正为 v{n}', 'Route revised to v{n}'],
  'explore.history': ['反馈与推导历史', 'Feedback & reasoning log'],
  'explore.feedbackLabel': ['反馈结果，继续推导', 'Report results & keep reasoning'],
  'explore.feedbackPh': [
    '做了什么实验 / 读了什么文献 / 跑了什么分析 / 观察到什么…越具体，推导越准',
    'What you ran, read or observed… the more specific, the sharper the reasoning',
  ],
  'explore.feedbackHint': [
    'Serendip 将对照原假说分析结果 → 重整证据墙逻辑 → 修正方案 → 给出下一步方向（⌘/Ctrl+Enter 发送）',
    'Serendip will compare against the hypothesis → re-organize the wall → revise the plan → propose next steps (⌘/Ctrl+Enter)',
  ],
  'explore.submit': ['提交反馈', 'Submit feedback'],
  'explore.nextRun': ['纳入反馈，开启下一轮研究', 'Fold in feedback · next run'],
  'explore.nextRunHint': ['把课题与反馈推导的证据作为聚焦点，开启一轮新的自主研究（研究期间钉上的反馈证据会保留在墙上）', 'Start a new autonomous run focused on this topic — feedback evidence pinned on the wall carries over'],
  'explore.feedbackBusyTitle': ['正在推导你的反馈…', 'Reasoning over your feedback…'],
  'explore.feedbackBusyBody': [
    '对照原假说分析结果 → 重整证据墙逻辑 → 修正方案 → 给出下一步方向。通常需要 30-90 秒，完成后证据墙会同步更新。',
    'Comparing against the hypothesis → re-organizing the wall → revising the plan → proposing next steps. Usually 30-90 seconds; the wall refreshes on completion.',
  ],
  'explore.verdict.supports': ['支持原假说', 'Supports'],
  'explore.verdict.contradicts': ['否定原假说', 'Contradicts'],
  'explore.verdict.mixed': ['部分支持 · 部分否定', 'Mixed'],
  'explore.verdict.inconclusive': ['尚无法判定', 'Inconclusive'],
  'explore.verdict.refined': ['问题被重新定义', 'Refined'],
  'topic.explore': ['探索方案', 'Explore'],
  'topic.exploreRounds': ['已探索 {n} 轮', '{n} rounds'],
  'topic.exploreOpen': ['打开探索面板（方案 · 反馈推导 · 下一步方向）', 'Open the exploration panel (plan · feedback reasoning · next steps)'],

  /* 活动日志 */
  'act.steps': ['研究步数', 'Steps'],
  'act.toolCalls': ['工具调用', 'Tool calls'],
  'act.llmCalls': ['LLM 推理', 'LLM calls'],
  'act.evidence': ['证据节点', 'Evidence cards'],
  'act.emptyTitle': ['暂无活动记录', 'No activity yet'],
  'act.emptyBody': [
    'Agent 的每一步思考、每一次数据库检索、每一条证据落墙，都会在这里留下完整的时间线。',
    'Every reasoning step, database query and evidence pin lands here as a complete timeline.',
  ],
  'act.phaseSwitch': ['阶段切换 → {phase}', 'Phase → {phase}'],

  /* 证据墙标签页 */
  'canvas.loading': ['正在展开软木板…', 'Unrolling the corkboard…'],
  'canvas.count': ['{n} 张卡片 · {m} 条连线', '{n} cards · {m} links'],
  'canvas.hint': ['拖动卡片可重新排布 · 点击卡片查看详情', 'Drag to rearrange · click a card for details'],
  'canvas.addNote': ['添加素材', 'Add card'],
  'canvas.emptyTitle': ['证据墙还是空的', 'The wall is empty'],
  'canvas.emptyBody': [
    '先在对谈室和 Serendip 聊聊你的好奇心；需求清晰后它会自动开始自主调研——检索到的文献证据、假说与洞见会被一张张钉到这里，最终提炼出的「深研课题卡」会醒目地钉在最右侧课题栏。',
    'Chat with Serendip about your curiosity first; once the need is clear it starts researching on its own — evidence, hypotheses and insights get pinned here one by one, and the distilled “research topic” cards land prominently in the rightmost column.',
  ],
  'canvas.legend': ['图例', 'Legend'],
  'canvas.organize': ['一键整理', 'Tidy up'],
  'canvas.organizeHint': [
    '按「课题 → 假说 → 证据 → 来源 → 深研课题」语义分列重新排布全部卡片',
    'Re-arrange all cards into semantic columns: question → hypothesis → evidence → source → topic',
  ],
  'canvas.organized': ['画布已重新整理', 'Canvas re-organized'],
  'canvas.stamp': ['灵感引擎 · 证据档案', 'EVIDENCE ARCHIVE'],
  'canvas.searchPh': ['搜索卡片：标题 / 正文 / 标签 / 来源…', 'Search cards: title / body / tags / source…'],
  'canvas.searchClear': ['清除搜索', 'Clear search'],
  'canvas.searchHits': ['{n}/{m} 张匹配', '{n}/{m} matched'],
  'canvas.searchNoHit': ['没有匹配的卡片', 'No matching cards'],
  'canvas.filterLabel': ['类型', 'Kind'],
  'canvas.filterHint': ['按卡片类型筛选显示', 'Filter visible cards by kind'],
  'canvas.filterReset': ['重置筛选', 'Reset filter'],
  'canvas.levelLabel': ['证据等级', 'Evidence level'],
  'canvas.levelFilterHint': ['按证据等级筛选显示', 'Filter evidence cards by level'],

  /* 添加素材对话框 */
  'note.title': ['添加素材', 'Add a card'],
  'note.kind': ['类型', 'Type'],
  'note.titleLabel': ['标题 *', 'Title *'],
  'note.details': ['详情', 'Details'],
  'note.source': ['来源链接', 'Source URL'],
  'note.tags': ['标签', 'Tags'],
  'note.phTitle': ['如：实验室测到的异常数据点', 'e.g. an odd data point from your bench'],
  'note.phDetails': ['具体的事实、数据或背景——越具体，Agent 用得越好', 'Concrete facts, data or context — the more specific, the better the agent can use it'],
  'note.phUrl': ['https://…（可选）', 'https://… (optional)'],
  'note.phTags': ['逗号分隔，如：宏基因组, 帕金森（可选）', 'Comma-separated, e.g. metagenomics, Parkinson (optional)'],
  'note.cancel': ['取消', 'Cancel'],
  'note.submit': ['钉上证据墙', 'Pin to the wall'],
  'note.needTitle': ['给这张素材卡一个标题吧', 'Give the card a title'],
  'note.added': ['素材已钉上证据墙，Agent 将在检查点纳入', 'Card pinned — the agent will fold it in at the next checkpoint'],
  'note.failed': ['添加失败', 'Failed to add'],

  /* 启动研究对话框 */
  'rd.start': ['启动自主研究', 'Start autonomous research'],
  'rd.continue': ['继续自主研究', 'Continue autonomous research'],
  'rd.continuingNote': [
    'Agent 将基于当前证据墙（{n} 张卡片）与既有结论继续推进，而不是从头再来。',
    'The agent will build on the current wall ({n} cards) and prior conclusions instead of starting over.',
  ],
  'rd.focus': ['本轮聚焦点（可选）', 'Focus for this round (optional)'],
  'rd.focusPh': [
    '留给 Agent 的指示，如：重点验证 H1 假说 / 检索近三年 CRISPR 脱靶研究 / 我的实验室有帕金森患者宏基因组数据可接入…',
    'Instructions for the agent, e.g. focus on testing H1 / survey recent CRISPR off-target studies / my lab has Parkinson metagenomics data…',
  ],
  'rd.budget': ['研究预算', 'Research budget'],
  'rd.budgetNote': [
    '研究期间你可随时补充素材或暂停；Agent 遇到只有你知道的关键信息时会主动提问。',
    'You can add notes or pause anytime; the agent will ask when it needs something only you know.',
  ],
  'rd.cancel': ['取消', 'Cancel'],
  'rd.launch': ['启动研究', 'Launch'],
  'rd.started': ['研究已启动，Agent 正在部署…', 'Research launched — the agent is deploying…'],
  'rd.continued': ['新一轮研究已启动，Agent 正在部署…', 'New round launched — the agent is deploying…'],
  'rd.failed': ['启动失败', 'Failed to start'],
  'rd.presetNote': ['聚焦点已预填自探索课题与反馈，可修改', 'Focus pre-filled from the explored topic & feedback — editable'],

  /* 卡片检视器 */
  'ins.pinnedAt': ['收录于 {time}', 'Pinned {time}'],
  'ins.unstar': ['取消星标', 'Unstar'],
  'ins.star': ['星标这条素材', 'Star this card'],
  'ins.noContent': ['（无详细内容）', '(no content)'],
  'ins.detail': ['深度解读', 'In-depth reading'],
  'ins.citation': ['文献引用', 'Citation'],
  'ins.openSource': ['打开原文：{url}', 'Open source: {url}'],
  'ins.sourceLink': ['原文链接', 'Source link'],
  'ins.confidence': ['置信度', 'Confidence'],
  'ins.statusStrong': ['证据扎实', 'Solid evidence'],
  'ins.statusWeak': ['证据偏弱', 'Weak evidence'],
  'ins.statusContradicted': ['存在矛盾', 'Contradicted'],
  'ins.relations': ['关系网络', 'Connections'],
  'ins.userNote': ['该素材由你手动钉上，Agent 会将其纳入研究上下文', 'You pinned this card manually — the agent will fold it into its research context'],

  /* 主布局 */
  'app.initFailed': ['初始化失败：{msg}（请确认 agent-service 正在运行）', 'Init failed: {msg} (is agent-service running?)'],
  'app.footerTagline': ['生物科研灵感引擎', 'Bio-research inspiration engine'],
  'app.footerSources': ['证据墙数据来自 PubMed / Europe PMC / OpenAlex / UniProt / NCBI / PDB', 'Evidence from PubMed / Europe PMC / OpenAlex / UniProt / NCBI / PDB'],
  'app.footerDisclaimer': ['AI 生成内容仅供研究启发，请以原始文献为准', 'AI-generated content is for inspiration only — verify against the original literature'],
  'app.mobileChat': ['对谈', 'Chat'],
  'app.mobileCanvas': ['证据墙', 'Wall'],
  'app.mobileNarrative': ['综述', 'Review'],
  'app.mobileDirections': ['深研', 'Paths'],
  'app.mobileQuestions': ['问题', 'Questions'],

  /* LLM 配置对话框 */
  'llm.title': ['LLM 配置', 'LLM Settings'],
  'llm.provider': ['供应商', 'Provider'],
  'llm.providerCount': ['{n} 家可选', '{n} available'],
  'llm.keyless': ['无需 Key', 'Keyless'],
  'llm.modelsCount': ['{n} 个模型', '{n} models'],
  'llm.urlKey': ['填 URL + Key', 'URL + Key'],
  'llm.getKey': ['获取 API Key', 'Get an API key'],
  'llm.model': ['模型', 'Model'],
  'llm.builtinNote': ['内置网关由环境固定', 'fixed by the environment'],
  'llm.selectModel': ['选择模型', 'Select a model'],
  'llm.modelPh': ['模型 ID，如 deepseek-chat / gpt-4o', 'Model ID, e.g. deepseek-chat / gpt-4o'],
  'llm.fetchList': ['获取列表', 'Fetch list'],
  'llm.manualModel': ['或手填模型 ID（不在列表中时）', 'Or type a model ID not in the list'],
  'llm.fetchedNote': ['已从 {name} 拉取 {n} 个模型', 'Fetched {n} models from {name}'],
  'llm.notInList': ['当前模型不在列表中，已切换为 {model}', '{model} is not in the list — switched'],
  'llm.fetchFailed': ['获取模型列表失败：{msg}', 'Failed to fetch models: {msg}'],
  'llm.noList': ['未获取到模型列表，使用内置目录', 'No models returned — using the built-in catalog'],
  'llm.apiKey': ['API Key', 'API Key'],
  'llm.keyConfigured': ['已配置（填写可覆盖）', 'Configured (type to override)'],
  'llm.keyPhKeyless': ['本地服务无需 Key，可留空', 'Local service needs no key'],
  'llm.keyPh': ['sk-…（{env}）', 'sk-… ({env})'],
  'llm.keyNote': [
    '填写后自动拉取该供应商的模型列表。Key 只保存在本机 agent-service 的 SQLite 中，不经过任何第三方；留空时读取环境变量 {env}。',
    'Typing a key auto-fetches the provider’s model list. Keys stay in the local agent-service SQLite only, never routed elsewhere; leave empty to fall back to the {env} environment variable.',
  ],
  'llm.baseUrl': ['Base URL', 'Base URL'],
  'llm.urlNoteCustom': ['必填：任何 OpenAI 兼容端点（/chat/completions）', 'Required: any OpenAI-compatible endpoint (/chat/completions)'],
  'llm.urlNoteDefault': ['留空使用默认地址；支持代理或私有部署', 'Leave empty for the default endpoint; proxies and private deployments supported'],
  'llm.temperature': ['采样温度', 'Sampling temperature'],
  'llm.tempPh': ['留空 = 供应商默认', 'Empty = provider default'],
  'llm.tempHint': ['0–2；调研类建议 0.2–0.7', '0–2; 0.2–0.7 recommended for research'],
  'llm.thinking': ['长链推理（thinking）', 'Extended reasoning (thinking)'],
  'llm.thinkingNote': ['内置网关专属；DeepSeek R1 类模型由服务端原生推理', 'Built-in gateway only; R1-style models reason natively server-side'],
  'llm.test': ['测试连接', 'Test connection'],
  'llm.testOk': ['连接正常 · {model} · {ms}ms', 'Connected · {model} · {ms}ms'],
  'llm.testReply': [' · 回复「{reply}」', ' · replied “{reply}”'],
  'llm.testFailed': ['连接失败 · {provider}/{model}', 'Failed · {provider}/{model}'],
  'llm.save': ['保存配置', 'Save'],
  'llm.cancel': ['取消', 'Cancel'],
  'llm.readFailed': ['读取配置失败：{msg}', 'Failed to load settings: {msg}'],
  'llm.saved': ['LLM 配置已保存，下次调用即生效', 'Saved — effective on the next call'],
  'llm.needKey': ['请填写 API Key，或切回内置网关', 'API key required, or switch back to the built-in gateway'],
  'llm.needUrl': ['自定义端点需要填写 Base URL', 'Custom endpoint needs a Base URL'],
  'llm.saveFailed': ['保存失败：{msg}', 'Failed to save: {msg}'],
  'llm.customUrlFirst': ['自定义端点需要先填写 Base URL', 'Enter the Base URL first'],
  'llm.needKeyFirst': ['请先填写 API Key', 'Enter the API key first'],

  /* 卡片（画布节点内） */
  'card.conf': ['置信', 'conf'],
  'card.gapFlag': ['待查', 'To probe'],

  /* 深研课题卡（topic 节点） */
  'topic.recommended': ['推荐深挖', 'Recommended'],
  'topic.columnHint': ['课题栏 · 值得深挖的方向', 'Topic column · worth pursuing'],
} as const;

export type TKey = keyof typeof DICT;

/** 模板插值：{key} → 参数值 */
export function fmt(template: string, params: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, k: string) => String(params[k] ?? ''));
}

/** 组件内取词钩子：t('key') → 当前语言文案
 *  useCallback 保证 t 在语言不变时引用稳定（避免进入 effect deps 造成循环） */
export function useT(): (key: TKey) => string {
  const lang = useI18n((s) => s.lang);
  const idx = lang === 'en' ? 1 : 0;
  return useCallback((key: TKey) => DICT[key][idx], [idx]);
}

/* ---------------- 标签表（语言相关） ---------------- */

export const NODE_KIND_LABEL: Record<NodeKind, Record<Lang, string>> = {
  question: { zh: '核心问题', en: 'Question' },
  hypothesis: { zh: '假说', en: 'Hypothesis' },
  evidence: { zh: '证据', en: 'Evidence' },
  insight: { zh: '洞见', en: 'Insight' },
  source: { zh: '文献源', en: 'Source' },
  gap: { zh: '待查', en: 'To probe' },
  topic: { zh: '深研课题', en: 'Research Topic' },
};

/** 证据等级标签（Task 20）：徽章 / 筛选 chip / 检视器共用；语义与配色见 EVIDENCE_LEVEL_COLOR */
export const EVIDENCE_LEVEL_LABEL: Record<EvidenceLevel, Record<Lang, string>> = {
  user: { zh: '一手数据', en: 'User data' },
  rct: { zh: '临床RCT', en: 'Clinical RCT' },
  cohort: { zh: '队列研究', en: 'Cohort' },
  animal: { zh: '动物因果', en: 'Animal causal' },
  invitro: { zh: '体外/细胞', en: 'In-vitro' },
  computational: { zh: '计算推断', en: 'Computational' },
};

export const EDGE_RELATION_LABEL: Record<EdgeRelation, Record<Lang, string>> = {
  supports: { zh: '支持', en: 'Supports' },
  contradicts: { zh: '矛盾', en: 'Contradicts' },
  relates: { zh: '相关', en: 'Relates' },
  derives: { zh: '推出', en: 'Derives' },
  answers: { zh: '回答', en: 'Answers' },
};

export const PHASE_LABEL: Record<SessionPhase, Record<Lang, string>> = {
  interview: { zh: '苏格拉底访谈', en: 'Socratic interview' },
  planning: { zh: '制定方案', en: 'Planning' },
  investigating: { zh: '文献调研中', en: 'Surveying literature' },
  synthesizing: { zh: '综合综述中', en: 'Synthesizing' },
  awaiting_user: { zh: '等你回应', en: 'Awaiting you' },
  done: { zh: '已完成', en: 'Completed' },
};

export const STATUS_LABEL: Record<AgentStatus, Record<Lang, string>> = {
  idle: { zh: '待命', en: 'idle' },
  thinking: { zh: '思考中', en: 'thinking' },
  running: { zh: '进行中', en: 'running' },
  paused: { zh: '已暂停', en: 'paused' },
  awaiting_user: { zh: '等待你的回应', en: 'awaiting your input' },
  done: { zh: '已完成', en: 'done' },
  error: { zh: '出错', en: 'error' },
  interrupted: { zh: '已中断', en: 'interrupted' },
};

export const AGENT_FACE_LABEL: Record<AgentFace, Record<Lang, string>> = {
  interviewer: { zh: '访谈者', en: 'Interviewer' },
  planner: { zh: '规划师', en: 'Planner' },
  investigator: { zh: '调研员', en: 'Investigator' },
  synthesizer: { zh: '综合分析师', en: 'Synthesizer' },
};

/** 工具名（活动日志时间线） */
export const TOOL_LABEL: Record<string, Record<Lang, string>> = {
  pubmed_search: { zh: 'PubMed 检索', en: 'PubMed search' },
  pubmed_fetch: { zh: 'PubMed 摘要精读', en: 'PubMed abstract read' },
  europepmc_search: { zh: 'Europe PMC 检索', en: 'Europe PMC search' },
  openalex_search: { zh: 'OpenAlex 检索', en: 'OpenAlex search' },
  uniprot_search: { zh: 'UniProt 蛋白查询', en: 'UniProt lookup' },
  ncbi_gene: { zh: 'NCBI 基因查询', en: 'NCBI Gene lookup' },
  pdb_search: { zh: 'PDB 结构检索', en: 'PDB search' },
  taxonomy_search: { zh: 'Taxonomy 物种查询', en: 'Taxonomy lookup' },
  clinvar_search: { zh: 'ClinVar 变异检索', en: 'ClinVar search' },
  web_search: { zh: 'Web 搜索', en: 'Web search' },
  web_read: { zh: '网页精读', en: 'Web page read' },
  add_evidence: { zh: '收录证据', en: 'Pin evidence' },
  link_evidence: { zh: '建立关联', en: 'Link cards' },
  update_evidence: { zh: '更新证据', en: 'Update card' },
  note_gap: { zh: '记录空白', en: 'Note gap' },
  ask_user: { zh: '向用户提问', en: 'Ask user' },
  finish_task: { zh: '任务小结', en: 'Task wrap-up' },
};
